import type { Metadata } from "next";
import { Merriweather } from "next/font/google";
import "./globals.css";
import { handleClientScriptLoad } from "next/script";

const merriweather = Merriweather({ subsets: ["latin"], weight: "300" });

export const metadata: Metadata = {
  title: "Luminary Visual's",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-[#fdf9f8]">
      <body className={merriweather.className}>{children}</body>
    </html>
  );
}
